sudo: required

services:
    - docker

before_install:
    - echo "Building the app"
    - docker build -f Dockerfile.dev -t prashantcd/react-docker-travis .

script:
    - docker run prashantcd/react-docker-travis npm run test -- --coverage
