sudo: required

services:
    - docker

before_install:
    - echo "Building the app"
    - docker build -f Dockerfile.dev -t prashantcd/react-docker-travis .

script:
    - docker run prashantcd/react-docker-travis npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "react-docker-travis"
    env: "ReactDockerTravis-env"
    bucket_name: "elasticbeanstalk-us-east-1-597335515095"
    bucker_path: "react-docker-travis"

    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
